from discord.ext import commands
import colorama
from colorama import Fore
import asyncio
from keep_alive import keep_alive

import os



prefix = "-"


keep_alive()
token = os.getenv("TOKEN")

#---------------#

bot = commands.Bot(command_prefix=prefix,
                   help_command=None,
                   case_insensitive=True,
                   self_bot=True)



@bot.event
async def on_ready():
  channel =bot.get_channel(890904462191894548)
  await channel.send('banbypass is now **enabled**!')
  global dmcs
  dmcs = True
  while dmcs:
        async with channel.typing():
          await asyncio.sleep(5)
          await channel.send('owo daily')
          await asyncio.sleep(5)
          await channel.send('owo lb all')     
          await channel.send('o use 57')
          await asyncio.sleep(19)
          await channel.send('o use 56')
          await asyncio.sleep(23)
          await channel.send('o use 55')
          await asyncio.sleep(20)
          await channel.send('o use 54')
          await asyncio.sleep(20)
          await channel.send('o use 53')
          await asyncio.sleep(16)
          await channel.send('o use 52')
          await asyncio.sleep(20)
          await channel.send('o use 51')
          await asyncio.sleep(20)
          await channel.send('o use 71')
          await asyncio.sleep(20)
          await channel.send('o use 70')
          await asyncio.sleep(23)
          await channel.send('o use 69')
          await asyncio.sleep(20)
          await channel.send('o use 68')
          await asyncio.sleep(20)
          await channel.send('o use 67')
          await asyncio.sleep(14)
          await channel.send('o use 66')
          await asyncio.sleep(20)
          await channel.send('o use 65')
          await asyncio.sleep(20)
          await channel.send('o use 78')
          await asyncio.sleep(20)
          await channel.send('o use 77')
          await asyncio.sleep(22)
          await channel.send('o use 76')
          await asyncio.sleep(19)
          await channel.send('o use 75')
          await asyncio.sleep(18)
          await channel.send('o use 74')
          await asyncio.sleep(17)
          await channel.send('o use 73')
          await asyncio.sleep(20)
          await channel.send('o use 72')
          await asyncio.sleep(20)
          await asyncio.sleep(5)
          await channel.send('owo q')
          await asyncio.sleep(5)
          await bot.get_channel(884736883014389770).send('owo inv')
          await asyncio.sleep(5)
          await channel.send('owo lb all')
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(8)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(12)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(17)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(12)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(15)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(14)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(300) 

          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(8)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(14)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(12)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(4)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(12)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(16)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(14)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(4)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(11)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(900)

          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(8)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(14)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(12)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(4)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(12)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(16)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(14)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(4)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(11)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(900)

          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(8)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(12)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(17)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(12)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(15)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(14)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(1200)        
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(8)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(12)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(17)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(12)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(15)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(14)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(300) 

          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(8)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(14)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await asyncio.sleep(5)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(10)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(14)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(12)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(9)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(13)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(18)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(4)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(12)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(16)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(14)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(4)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(11)
          await channel.send('owoh')
          print(f"{Fore.GREEN}succefully owoh")
          await asyncio.sleep(15)
          await channel.send('pls beg')
          print(f"{Fore.GREEN}succefully sell")
          await channel.send('owo sell all')
          print(f"{Fore.GREEN}succefully owo sell all")
          await asyncio.sleep(11)
          await channel.send('owo cash')
          print(f"{Fore.GREEN}succefully cash")
          await asyncio.sleep(86400)		


keep_alive()
bot.run(token, bot=False)